# Generated by Django 2.2.12 on 2022-10-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='zoho_id',
            field=models.IntegerField(default=-1),
        ),
    ]
