# Generated by Django 4.1.2 on 2022-11-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_department_id_alter_function_id_alter_log_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='key',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
